using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ZombieFController : MonoBehaviour
{
    Transform player;
    float speed = 2f;
    SpriteRenderer spriteRenderer;
    public bool endGame = false;

    // Start is called before the first frame update
    void Start()
    {
        player = GameObject.Find("Player").transform;
        spriteRenderer = GetComponent<SpriteRenderer>();
    }

    // Update is called once per frame
    void Update()
    {
      if(!endGame) {
        transform.position = Vector3.MoveTowards(transform.position, player.position, Time.deltaTime * speed); 
        if(transform.position.x > player.position.x)
        {
            spriteRenderer.flipX = true;
        }
        else
        {
            spriteRenderer.flipX = false;
        }
      }
        
    }
}
